; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x23 y9 w111 h23 +0x200, Gage ID:
Gui Add, Edit, x144 y9 w187 h21
Gui Add, Text, x24 y38 w110 h23 +0x200, Results Message:
Gui Add, Edit, x144 y38 w188 h21
Gui Add, CheckBox, x144 y71 w120 h23, Set Printer
Gui Add, Button, x260 y133 w80 h23, &Execute

Gui Show, w365 h169, Window
Return

GuiEscape:
GuiClose:
    ExitApp
